services:
  - type: web
    name: digital-catalyst
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///instance/database.db
